### Required setup for the install test images.
# tmpfs and volumes are needed for systemd to work properly
# ARGS can be setup by the testing script, see README
version: '3.8'
services:
  install_test:
    container_name: install-test
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OSimage: "$OSimage"
        REPO: "$REPO"
        useproxy: "${useproxy:-no}"
        proxy: "$proxy"
    image: install_$OSimage_$REPO
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
       - "8443:443"

