### Required setup for the install test images.
# tmpfs and volumes are needed for systemd to work properly
# ARGS can be setup by the testing script, see README
version: '3.9'
services:
  install_test:
    container_name: install-test
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OSimage: "$OSimage"
        REPO: "$REPO"
        useproxy: "${useproxy:-without}"
        proxy: "${proxy:-}"
    image: $REPO/$OSimage
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    ports:
       - "8443:443"

