# tmpfs and volumes are needed for systemd to work properly
version: '3.8'
services:
  install_test:
    container_name: install-test
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OSimage: "$OSimage"
        REPO: "$REPO"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - bundle_testing
    ports:
       - "8443:443"

networks:
  bundle_testing:
    name: bundle_testing
    driver: bridge

