### Required setup for the install test images.
# tmpfs and volumes are needed for systemd to work properly
# ARGS can be setup by the testing script, see README

# Some defaults
x-ports:
  &default-ports
  - "8443:443"

x-tmpfs:
  &default-tmpfs
  - /run
  - /run/lock
  - /tmp

# Services
services:
  install_test_buster:
    container_name: install-test-buster
    privileged: true
    image: $REPO/debian:buster
    tmpfs: *default-tmpfs

  install_test_bullseye:
    container_name: install-test-bullseye
    privileged: true
    image: $REPO/debian:bullseye
    tmpfs: *default-tmpfs

  install_test_bookworm:
    container_name: install-test-bookworm
    privileged: true
    image: $REPO/debian:bookworm
    tmpfs: *default-tmpfs

  install_test_focal:
    container_name: install-test-focal
    privileged: true
    image: $REPO/ubuntu:focal
    tmpfs: *default-tmpfs

  install_test_9:
    container_name: install-test-9
    privileged: true
    image: $REPO/almalinux:9
    tmpfs: *default-tmpfs

  install_test_blueonyx:
    container_name: install-test-blueonyx
    privileged: true
    image: $REPO/rockylinux:blueonyx
    tmpfs: *default-tmpfs

  install_test_jammy:
    container_name: install-test-jammy
    privileged: true
    image: $REPO/ubuntu:jammy
    tmpfs: *default-tmpfs

  single_sanity:
    container_name: install-single-sanity
    privileged: true
    build:
      context: ../../../sanity-checking/
      dockerfile: Dockerfile-single
    image: single-sanity
