### Required setup for the install test images.
# tmpfs and volumes are needed for systemd to work properly
# ARGS can be setup by the testing script, see README

# Some defaults
x-ports:
  &default-ports
  - "8443:443"

x-tmpfs:
  &default-tmpfs
  - /run
  - /run/lock
  - /tmp

# Services
version: '3.9'
services:
  install_test_centos7:
    container_name: install-test-centos7
    privileged: true
    image: $REPO/centos:7
    tmpfs: *default-tmpfs
  
  install_test_almalinux8:
    container_name: install_test_almalinux8
    privileged: true
    image: $REPO/almalinux:8
    tmpfs: *default-tmpfs

  single_sanity:
    container_name: install-single-sanity
    privileged: true
    build:
      context: ../../../sanity-checking/
      dockerfile: Dockerfile-single
    image: single-sanity